from pathlib import Path
import sys

from PIL import Image


WIDTH = 320
HEIGHT = 240
LOGO_SIZE = 220
BACKGROUND = (8, 13, 18, 255)


def main() -> None:
    if len(sys.argv) != 3:
        raise SystemExit("usage: generate_channel_splash.py INPUT.png OUTPUT.cpp")

    source = Image.open(sys.argv[1]).convert("RGBA")
    source.thumbnail((LOGO_SIZE, LOGO_SIZE), Image.Resampling.LANCZOS)
    canvas = Image.new("RGBA", (WIDTH, HEIGHT), BACKGROUND)
    position = ((WIDTH - source.width) // 2, (HEIGHT - source.height) // 2)
    canvas.alpha_composite(source, position)

    values = []
    for red, green, blue, _alpha in canvas.get_flattened_data():
        values.append(((red >> 3) << 11) | ((green >> 2) << 5) | (blue >> 3))

    rows = []
    for offset in range(0, len(values), 16):
        rows.append("  " + ", ".join(f"0x{value:04X}" for value in values[offset:offset + 16]) + ",")

    output = """// Generated by tools/generate_channel_splash.py. Do not edit manually.
#include "splash565.h"

static const uint16_t splash565_data[320 * 240] PROGMEM = {
%s
};

const tgx::Image<tgx::RGB565> splash565(
    reinterpret_cast<const tgx::RGB565 *>(splash565_data), 320, 240);
""" % "\n".join(rows)
    Path(sys.argv[2]).write_text(output, encoding="ascii", newline="\n")


if __name__ == "__main__":
    main()
