from pathlib import Path
import sys

from PIL import Image


WIDTH = 320
HEIGHT = 240
LOGO_SIZE = 220
BACKGROUND = (8, 13, 18, 255)


def main() -> None:
    if len(sys.argv) != 3:
        raise SystemExit("usage: generate_channel_splash.py INPUT.png OUTPUT.cpp")

    output_path = Path(sys.argv[2])
    symbol = output_path.stem
    source = Image.open(sys.argv[1]).convert("RGBA")
    scale = min(LOGO_SIZE / source.width, LOGO_SIZE / source.height)
    source = source.resize(
        (round(source.width * scale), round(source.height * scale)),
        Image.Resampling.LANCZOS,
    )
    canvas = Image.new("RGBA", (WIDTH, HEIGHT), BACKGROUND)
    position = ((WIDTH - source.width) // 2, (HEIGHT - source.height) // 2)
    canvas.alpha_composite(source, position)

    values = []
    for red, green, blue, _alpha in canvas.get_flattened_data():
        values.append(((red >> 3) << 11) | ((green >> 2) << 5) | (blue >> 3))

    rows = []
    for offset in range(0, len(values), 16):
        rows.append("  " + ", ".join(f"0x{value:04X}" for value in values[offset:offset + 16]) + ",")

    output = """// Generated by tools/generate_channel_splash.py. Do not edit manually.
#include "%s.h"

static const uint16_t %s_data[320 * 240] PROGMEM = {
%s
};

const tgx::Image<tgx::RGB565> %s(
    reinterpret_cast<const tgx::RGB565 *>(%s_data), 320, 240);
""" % (symbol, symbol, "\n".join(rows), symbol, symbol)
    output_path.write_text(output, encoding="ascii", newline="\n")


if __name__ == "__main__":
    main()
